# Generated by Django 4.2.9 on 2024-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jordan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('colorway', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('designer', models.CharField(max_length=100)),
                ('materials', models.CharField(max_length=150)),
            ],
        ),
    ]
