# Generated by Django 4.2.9 on 2024-02-02 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.CharField(choices=[('c', 'Clean'), ('w', 'Wear')], default='c', max_length=1)),
                ('jordan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jordan')),
            ],
        ),
    ]
